// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3N6avyqAsGfFrsz-oqWaeT7uq1ZKikY4',
    appId: '1:545349136515:web:529ad909a8b1359655abb6',
    messagingSenderId: '545349136515',
    projectId: 'technofy-b63d0',
    authDomain: 'technofy-b63d0.firebaseapp.com',
    storageBucket: 'technofy-b63d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4MvV4coQVQLw4eQJaaB1awI0aFplS_sc',
    appId: '1:545349136515:android:2cdd7b94693a9b8f55abb6',
    messagingSenderId: '545349136515',
    projectId: 'technofy-b63d0',
    storageBucket: 'technofy-b63d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx-EeFrJ-2l71wdDomq2rLKmrpO8aAfGw',
    appId: '1:545349136515:ios:9a13697ab1098f1155abb6',
    messagingSenderId: '545349136515',
    projectId: 'technofy-b63d0',
    storageBucket: 'technofy-b63d0.appspot.com',
    iosBundleId: 'com.example.universe7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx-EeFrJ-2l71wdDomq2rLKmrpO8aAfGw',
    appId: '1:545349136515:ios:9a13697ab1098f1155abb6',
    messagingSenderId: '545349136515',
    projectId: 'technofy-b63d0',
    storageBucket: 'technofy-b63d0.appspot.com',
    iosBundleId: 'com.example.universe7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3N6avyqAsGfFrsz-oqWaeT7uq1ZKikY4',
    appId: '1:545349136515:web:4a692ea65af6898355abb6',
    messagingSenderId: '545349136515',
    projectId: 'technofy-b63d0',
    authDomain: 'technofy-b63d0.firebaseapp.com',
    storageBucket: 'technofy-b63d0.appspot.com',
  );
}
